language: python
python:
- '3.7'
install:
- pip install -e .
- cd develop
- python manage.py migrate
script:
- python manage.py test helpme
- cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: eg6m+lNkyl9NWFqhZxCPWZgYU+KtVyLoi99KfEbBN88Q7+B+IUIMTbIfykUUbmim55JiOfTeEIeWDljY9PweXqq5GkUTp8lHkt+++mvHhWURnJ3M5MAnUAeKW1E8Cvv9B6qaDevpeLXo7Pfolxl7Ncu6GLe6zu8HE0Cng1Hsui15kM665GUMA4wk8+EyXzTQYWxa2ObtQr3aBlKt5JMYiK7/0d+fkY8vjSOux/ClfSMtXC89DLyi6d8f9kzq32WKgMwsK89p9D14qflKHMGCKIBYT8D7M+kIQ8QN0a2FfPX7rlFe4ZX2o+TmONV6+bFQPY1qFm9hQR5ZNQI0yEWhe09kjqRr9UVCYdVMPINbbAR+W2utw0F7FAenWHuK85FDQkNEgxCIilNGW1P2t51PP+tr1DmUfoa5lrO1nfCz6jzpyKK3wsedLaD4OBuFXIN6azc9cxEGAeGeaXBAGZJGcZuxcs8RgsfVxSJAQXFtuexctTMYp55V6rb1endt1NvG02MaxMvli9y276GPSt9mwEe5+GMiOyzoAdY8u3RXl/yuNlPNThe/gIMD7zDGDG3QWlIgQPjFA1tBndFVEfHxJ0Bz7f45z0W8iOqtMjQRmedxpPeFvH98LnMIW2RntGf7LaHVy7p4eH1tZGpg3WRluE67oteX62nOxFEUZE+lmdw=
