# Generated by Django 3.1 on 2021-06-16 21:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpme', '0011_auto_20201106_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Comment'), (2, 'Sales'), (3, 'Help'), (4, 'Bug'), (5, 'Contact')], max_length=9, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.IntegerField(choices=[(1, 'Comment'), (2, 'Sales'), (3, 'Help'), (4, 'Bug'), (5, 'Contact')], verbose_name='Category'),
        ),
    ]
