# Generated by Django 4.0 on 2022-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpme', '0012_auto_20210616_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='helpme.Ticket'),
        ),
    ]
