# Generated by Django 3.2.12 on 2022-03-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpme', '0013_alter_ticket_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='related_to',
            field=models.ManyToManyField(blank=True, related_name='_helpme_ticket_related_to_+', to='helpme.Ticket'),
        ),
    ]
